### ISSUE TITLE
Log work into jira only first time

### ISSUE THREAD

**Issue by josefhulkauni** [bubblefoil/p4u-worklogger#15]
When I open Work Log dialog in WTM, only in first time is work logged into jira too, other logs not. I have to close and open dialog again. 
tested in Linux (4.18.14) and Chrome (69.0.3497.100)

**Comment by bubblefoil** [comment]
The buttons are probably re-rendered.
Added callback that registers listeners after work is logged to JIRA.
Fixed in 2.0.5
